In [1]:
import torch

In [2]:
# Number
t1 = torch.tensor(4.)
print(t1)
t1.shape # prints an empty array because this is acaler

tensor(4.)


torch.Size([])

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [5]:
# Matrix
t3 = torch.tensor([
    [5, 6],
    [7, 8],
    [9, 10]
])
print(t3)
t3.shape

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])


torch.Size([3, 2])

In [6]:
# 3-Dimensional Array
t4 = torch.tensor([
 [
     [11, 12, 13],
     [13, 14, 15]
 ],
 [
     [15, 16, 17],
     [17, 18, 19.]
 ]
])
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

# Tensor Operations and gradients

In [7]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
print("X: ",x)
print("Shape of X: ",x.shape)

print("\nW: ",w)
print("Shape of W: ",w.shape)

print("\nB: ",b)
print("Shape of B: ",b.shape)

X:  tensor(3.)
Shape of X:  torch.Size([])

W:  tensor(4., requires_grad=True)
Shape of W:  torch.Size([])

B:  tensor(5., requires_grad=True)
Shape of B:  torch.Size([])


In [8]:
#Arithmatic Operations
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

# What makes PyTorch special
We can automatically compute the derivative of `y` w.r.t the tensors that have `requires_grad` set to `True`
# What is Gradient?
Well it is the another term for derivative and it is used mainly when dealing with matrises and tensors.

In [9]:
# Computing derivatives
y.backward()
# Now the derivatives of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors

In [10]:
# Disaplying Derivatives
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


#### ------Basic intro to tensors and its operation in pytorch-----
#### ----------------The End---------

## Introperability with Numpy

In [22]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
print(x)
print(x.shape)
print(x.dtype)

[[1. 2.]
 [3. 4.]]
(2, 2)
float64


We can convert a Numpy array to PyTorch tensors using `torch.from_numpy`

In [24]:
# Converting the numpy array to a torch tensor.
y = torch.from_numpy(x)
print(y)
y.dtype

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


torch.float64

We can also convert a PyTorch tensor to a numpy array using the`.numpy` method of a tensor

In [26]:
# Converting a torch tensor to a numpy array
z = y.numpy()
print(z)
z.dtype

[[1. 2.]
 [3. 4.]]


dtype('float64')