# Deep Learning with PyTorch: Zero to GANs, Assignment 01
### Top five tensor functions chosen by me:-

As an assignment towards the lecture 1, I have chosen this 5 functions. According to me this 5 functions are must for every Deep Learning with PyTorch enthusiast.

- torch.randn()
- torch.sort()
- torch.pow()
- torch.round()
- torch.det()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.randn()
`
torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
`<br>
Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
<br>
The shape of the tensor is defined by the variable argument size.

### Its has the following parameters

- **size (int...)** – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

- **out (Tensor, optional)** – the output tensor.

- **dtype (torch.dtype, optional)** – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).

- **layout (torch.layout, optional)** – the desired layout of returned Tensor. Default: torch.strided.

- **device (torch.device, optional)** – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

- **requires_grad (bool, optional)** – If autograd should record operations on the returned tensor. Default: False.

In [2]:
# Example 1 - working (change this)
x = torch.randn(4,3)
print('X: ',x)

X:  tensor([[-0.5920, -0.2184, -1.2465],
        [-1.4039, -0.6418, -0.2849],
        [-0.9071,  1.6676,  0.1368],
        [ 0.8382, -0.0290,  2.0863]])


In the above example I have created a tensor having 4 Rows and 3 Coulumn with 12 random elements.

In [3]:
# Example 2 - working
y = torch.randn(2,4,3)
print('Y: \n',y)

Y: 
 tensor([[[ 0.6822,  0.1700, -0.4136],
         [-0.6059, -0.2416, -1.6822],
         [-0.6159,  0.3158,  0.2123],
         [ 1.8296,  0.3534, -1.4471]],

        [[-0.3172,  2.7545,  0.3334],
         [-2.0384,  1.5353, -1.3347],
         [ 1.5819, -1.3099, -0.5110],
         [-0.7074, -0.8412, -1.1446]]])


In the above example I have created a 3-D tensor having 2 subtensors of 4 Rows and 3 Coloumn.

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.randn()
z

TypeError: randn() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


The above example produces an error because `randn()` function requires at least one positional arguments: "**size**" without which all the other arguments will not work too.

This is the most widely used function with PyTorch and is also the most usefull one. With this function we can create any `size` or `dimension` tensor. One of the main use of `randn()` function in Deep Learning is when we need to create or initialize an tensor of random elements for `weights` and `biases` to work with different regression models in Machine Learning.

---------------------

## Function 2 - torch.sort()
`torch.sort(input, dim=-1, descending=False, out=None) -> (Tensor, LongTensor)`

This function sorts the elements of the `input` tensor along a given dimension in ascending order by value.

**Its has the following parameters**
- **input (Tensor)** – the input tensor.

- **dim (int, optional)** – the dimension to sort along

- **descending (bool, optional)** – controls the sorting order (ascending or descending)

- **out (tuple, optional)** – the output tuple of (Tensor, LongTensor) that can be optionally given to be used as output buffers



In [5]:
# Example 1 - working
a = torch.randn(10,20)
sortedA, indicesA = torch.sort(a, descending=False)
print('Sorted tensor elements in Ascending order: \n',sortedA)

Sorted tensor elements in Ascending order: 
 tensor([[-2.1991, -2.0583, -1.0254, -0.7572, -0.6040, -0.5535, -0.4792, -0.4002,
         -0.2411, -0.2043, -0.1280, -0.0542, -0.0376,  0.2922,  0.3992,  0.6432,
          0.8323,  0.9499,  1.3544,  1.5031],
        [-1.0499, -0.8839, -0.6659, -0.5950, -0.5275, -0.5081, -0.3294, -0.1818,
         -0.0611, -0.0421,  0.1122,  0.1476,  0.2813,  0.3311,  0.3442,  0.3993,
          0.8177,  1.5280,  1.5741,  1.5783],
        [-1.1427, -1.0190, -0.8861, -0.6085, -0.5874, -0.3841, -0.1969, -0.0128,
          0.3078,  0.4457,  0.4586,  0.5970,  0.6069,  0.6378,  0.6886,  1.3316,
          1.3765,  1.4102,  1.8743,  2.1062],
        [-1.8262, -0.8824, -0.6611, -0.5644, -0.3722, -0.2558, -0.2369, -0.1252,
         -0.0363, -0.0272,  0.0678,  0.2578,  0.2794,  0.4999,  0.5469,  0.6988,
          0.7285,  1.2892,  1.3993,  1.9027],
        [-2.0376, -1.2251, -1.2177, -0.9508, -0.6074, -0.5420, -0.4655, -0.2945,
         -0.2715, -0.1660, -0.1113,  0.062

In the above example with the help of `torch.sort()` I have sorted the elements of the `10,20` matrix in ascending order row wise.

In [6]:
# Example 2 - working
b = torch.randn(100)
sortedb, indicesb = torch.sort(b,descending=False)
print('Sorted Elements: \n',sortedb)
print('Indices of the elements according to their values: \n',indicesb)

Sorted Elements: 
 tensor([-2.2386, -1.9578, -1.8151, -1.8102, -1.6286, -1.5344, -1.4966, -1.3646,
        -1.3340, -1.2924, -1.2729, -1.2490, -1.2048, -1.0744, -1.0260, -1.0049,
        -0.9293, -0.9044, -0.8967, -0.8874, -0.8132, -0.7885, -0.7380, -0.7322,
        -0.7133, -0.7097, -0.6034, -0.6008, -0.5704, -0.5551, -0.5477, -0.5189,
        -0.5122, -0.4614, -0.4600, -0.4398, -0.3522, -0.3313, -0.3249, -0.3135,
        -0.2706, -0.2665, -0.2540, -0.2260, -0.2100, -0.1766, -0.1604, -0.1532,
        -0.0835, -0.0614, -0.0196, -0.0164,  0.0356,  0.0755,  0.1059,  0.1065,
         0.1411,  0.1731,  0.1763,  0.2977,  0.3394,  0.3554,  0.3661,  0.3948,
         0.5412,  0.5459,  0.6806,  0.6894,  0.7074,  0.7098,  0.7113,  0.7214,
         0.7243,  0.7385,  0.7652,  0.7659,  0.7740,  0.8660,  0.8922,  0.9324,
         0.9618,  0.9774,  1.0168,  1.0367,  1.0454,  1.1301,  1.1315,  1.1347,
         1.1766,  1.2070,  1.2351,  1.2549,  1.4345,  1.4409,  1.4742,  1.4750,
         1.5117,  2.0

In the above example I have sorted a `1D` tensor with the help of `torch.sort()` function.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
sortedc = torch.sort(c)
print(sortedc)

NameError: name 'c' is not defined

The above example breaks because for the `torch.sort()` functions to operate, an argument which is previsoly present has to be provided.

The `torch.sort()` function  is used to sort the elements of any tensor in ascending or descending order according to their value, and also the `torch.sort()` returns the indices of the elements from `(0,n-1)` according to the values of the tensor elements.

---

## Function 3 - torch.pow()
`torch.pow(input, exponent, out=None) → Tensor`

This function Takes the power of each element in `input` with `exponent` and returns a tensor with the result.
`exponent` can be either a single `float` number or a Tensor with the same number of elements as input.

When exponent is a scalar value, the operation applied is:

**<center>out<sub>i</sub> = x<sub>i</sub><sup>exponent</sup></center>**
 
When exponent is a tensor, the operation applied is:

**<center>out<sub>i</sub> = x<sub>i</sub><sup>exponent<sub>i</sub></sup></center>**
 
When exponent is a tensor, the shapes of input and exponent must be broadcastable i.e., if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data)..

**Its has the following parameters**
- **input (Tensor)** – the input tensor.

- **exponent (float or tensor)** – the exponent value

- **out (Tensor, optional)** – the output tensor.


In [8]:
# Example 1 - working
p = torch.randn(10)
print('Value of P: \n',p)
p = torch.pow(p,2)
print('Value of P after applying .pow function: \n',p)

Value of P: 
 tensor([-1.3319, -0.6649, -0.1012, -1.0675,  1.0436,  1.2512,  0.9339, -0.4077,
        -0.7794, -0.2919])
Value of P after applying .pow function: 
 tensor([1.7740, 0.4421, 0.0102, 1.1395, 1.0891, 1.5655, 0.8722, 0.1662, 0.6075,
        0.0852])


In the above example I have squared each element of the `1D` tensor.

In [9]:
# Example 2 - working
q = torch.randn(3,4)
print('Value of q: \n',q)
q = torch.pow(q,-2)
print('Elements of q after dividing each element by itself raised to the power of 2: \n',q)

Value of q: 
 tensor([[ 0.1930,  0.8621, -0.0598, -0.8028],
        [-0.2263,  1.5123,  0.6414,  0.6192],
        [-0.4659, -1.1043, -1.0759,  0.2473]])
Elements of q after dividing each element by itself raised to the power of 2: 
 tensor([[ 26.8353,   1.3454, 279.9051,   1.5517],
        [ 19.5219,   0.4373,   2.4311,   2.6084],
        [  4.6068,   0.8201,   0.8639,  16.3479]])


In the above example I have divided each element by itself raised to the power of 2.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
r = torch.randn(4,5)
print('Value of r: \n',r)
r = torch.pow(-0.98)

Value of r: 
 tensor([[-1.1134,  0.4987,  1.3809, -0.2304,  1.8240],
        [-0.4886,  0.8074, -0.8462,  0.0382,  1.4625],
        [-0.4145,  1.0611, -1.1656,  0.3286, -0.1774],
        [ 0.5727,  0.3004, -1.4625, -0.1778,  0.4879]])


TypeError: pow() received an invalid combination of arguments - got (float), but expected one of:
 * (Tensor input, Tensor exponent, *, Tensor out)
 * (Number self, Tensor exponent, *, Tensor out)
 * (Tensor input, Number exponent, *, Tensor out)


The above example breaks beacuse the `torch.pow()` function requires an argument of the type matrix,number,Tensor etc to process them to that power.

The `torch.pow()` function is very usefull function when we are working with matrix, tensors, determinant etc. we can easily find the squares, cubes, of every element of a matrix.

---

## Function 4 - torch.round()
`torch.round(input, out=None) → Tensor`

Returns a new tensor with each of the elements of `input` rounded to the closest integer.

**Its has the following parameters**
- **input (Tensor)** – the input tensor.
- **out (Tensor, optional)** – the output tensor.


In [11]:
# Example 1 - working
m = torch.randn(50)*10
print('m: \n',m)
m = torch.round(m)
print('After rounding: \n',m)

m: 
 tensor([-12.3885,   3.8979,  -3.7547,  -7.5730,  -3.4935, -24.8415,   1.9059,
          0.1227,  15.7279,  -5.5311,   4.2793,  -1.3735,  -0.3351,  19.9994,
         -6.6800,   3.4005,   5.9941,  16.2860,   5.1336,   6.4227,   0.2689,
          4.3704,   6.2479, -19.8787,  -4.8099,   4.4244,  10.8032,   2.7058,
        -11.0726, -12.5349,  -0.8918, -10.6053,  -1.1584,   5.8533,   5.0602,
        -11.3950,  11.7124,  -0.5873,  -5.2842,  -2.7306, -11.1543,   6.0312,
         11.9412,   0.4816, -13.1112,  -8.0313,   8.1504, -11.9349,  14.1010,
          9.7258])
After rounding: 
 tensor([-12.,   4.,  -4.,  -8.,  -3., -25.,   2.,   0.,  16.,  -6.,   4.,  -1.,
         -0.,  20.,  -7.,   3.,   6.,  16.,   5.,   6.,   0.,   4.,   6., -20.,
         -5.,   4.,  11.,   3., -11., -13.,  -1., -11.,  -1.,   6.,   5., -11.,
         12.,  -1.,  -5.,  -3., -11.,   6.,  12.,   0., -13.,  -8.,   8., -12.,
         14.,  10.])


In the above example I have rounded of every element of a 1D matrix`m` to its closest integer

In [12]:
# Example 2 - working
n = torch.randn(10,5)*10
print('n: \n',n)
n = torch.round(n)
print('After rounding: \n',n)

n: 
 tensor([[-12.8345,  -2.9560,  -5.2553, -11.4309,  -4.6741],
        [  0.4952,   8.0011,  -0.6205,   5.2730,   0.4621],
        [ -8.9586,   0.6913,  14.3178,  -7.4346,  -9.2766],
        [ -5.5092, -11.0026,  -6.1492,  -2.7321, -11.9246],
        [ 17.8632,  -4.1838, -14.3068,  -1.9312,  -2.6807],
        [-12.7375,   5.4309,  16.4587,  -1.1173,  -3.9296],
        [-20.0374,  -1.1680,   9.6117,   0.8820,  12.3250],
        [ 13.0375,  -0.0316,   1.6852,  -9.7471,  -5.0131],
        [-10.7766,   2.4458,   0.3199,  19.8068, -13.3489],
        [-18.1848,   5.2997,   8.3156,  -1.8209,  -1.4442]])
After rounding: 
 tensor([[-13.,  -3.,  -5., -11.,  -5.],
        [  0.,   8.,  -1.,   5.,   0.],
        [ -9.,   1.,  14.,  -7.,  -9.],
        [ -6., -11.,  -6.,  -3., -12.],
        [ 18.,  -4., -14.,  -2.,  -3.],
        [-13.,   5.,  16.,  -1.,  -4.],
        [-20.,  -1.,  10.,   1.,  12.],
        [ 13.,  -0.,   2., -10.,  -5.],
        [-11.,   2.,   0.,  20., -13.],
        [-18.,  

In the above example I have rounded all elements of a 2D matrix `n` to its nearest integer value.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np
o = np.random.rand(5,3)
print('o: \n',o)
o = torch.round(o)

o: 
 [[0.31079312 0.1947487  0.5374745 ]
 [0.74277246 0.76638274 0.37522906]
 [0.02303948 0.35328497 0.50590677]
 [0.21403249 0.93415963 0.81676156]
 [0.31237431 0.11411553 0.84052887]]


TypeError: round(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

The above example breaks because the function `torch.round()` requires its input to be of the type `tensor` but the argument to it was provided of the type `numpy.ndarray`

The function `torch.round()` is verry usefull when we are working with datasets containing huge number of rows with elements of verry similar type with small differences. We can use this function to round of the decimal numbers and have a integer numbered dataset.

---

## Function 5 - torch.det()
`torch.det(input) → Tensor`

Calculates determinant of a square matrix or batches of square matrices.

One thing to **note** is that:<br>
Backward through `det()` internally uses SVD results when `input` is not invertible. In this case, double backward through `det()` will be unstable in when `input` doesn’t have distinct singular values. See `svd()` for details.

**It has only one parameter**
- **input (Tensor)** – the input tensor of size `(*, n, n)` where `*` is zero or more batch dimensions.


In [14]:
# Example 1 - working
g = torch.randn(5,5)
print('g: \n',g)
print('Determinant of g: \n',torch.det(g))

g: 
 tensor([[ 1.9468, -0.8990, -2.8976, -0.0991,  0.2804],
        [-2.0874, -1.5651, -0.6416,  1.0339, -0.9406],
        [ 1.1748,  1.7234, -0.7249,  0.2515,  0.4928],
        [ 0.9896,  0.2958,  0.2307,  0.9065, -0.3516],
        [ 0.0759, -1.2318, -0.0718,  1.3853, -0.7760]])
Determinant of g: 
 tensor(3.9412)


In the above example I have calculated the determinant of `g` matrix.

In [15]:
# Example 2 - working
h = torch.randn(3,5,5)
print('h: \n',h)
print('Determinant of h: \n',torch.det(h))

h: 
 tensor([[[-0.6988,  0.4830, -0.5798, -0.6708, -0.1348],
         [ 0.7242, -0.2111,  1.1545, -0.1202,  0.6138],
         [ 0.4436, -0.8853,  0.0058,  1.7501,  0.1185],
         [-1.3626,  0.8585,  0.9701, -0.9722, -1.4513],
         [-1.3129, -0.2418, -1.4145, -0.1343, -1.7309]],

        [[ 0.0678, -0.3322, -1.0623, -1.4052,  0.2504],
         [ 0.5199,  0.0791,  1.4029, -1.9736,  1.3660],
         [-2.3195,  0.8645, -1.0921, -0.9754, -1.3764],
         [ 1.1002, -0.2191, -2.1193, -0.4716, -1.6756],
         [ 0.2011,  0.6271, -1.7751, -0.4679,  2.0513]],

        [[ 0.8184, -0.6205, -0.6867, -0.7977,  0.5309],
         [ 0.4675,  0.7558, -0.6423, -1.4308, -0.6336],
         [-0.2454,  0.3314,  0.0300, -0.1960,  0.0865],
         [ 1.2832, -0.1300, -0.9258,  1.7563, -0.7155],
         [-0.0040,  0.5543,  0.8026, -0.7096,  0.2504]]])
Determinant of h: 
 tensor([  1.1341, -40.9796,  -1.2252])


In the above example we have found the determinant of 3 `2D` matrix with the help of `torch.det()` function.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
i = torch.randn(100)
print('i: \n',i)
print('Determinant of i: \n',torch.det(i))

i: 
 tensor([ 1.0126e+00, -3.4785e-01, -1.0242e+00, -1.1218e+00,  7.7651e-01,
        -9.2103e-01,  2.1521e-01,  7.5424e-01,  7.2489e-01, -9.6772e-01,
         1.2994e+00,  4.0843e-01, -7.7892e-01, -6.6552e-01,  1.2852e+00,
        -1.6347e+00, -1.8019e+00, -5.8304e-01, -7.1641e-03,  2.6614e+00,
        -9.0267e-01, -6.2085e-01, -8.9144e-01,  2.0517e-01, -6.3365e-01,
         7.0386e-01,  5.3186e-01, -7.7965e-01,  2.9091e-01,  1.9445e-01,
         9.3103e-01, -9.8945e-01, -1.9075e+00, -1.6427e-01, -1.6112e-01,
        -7.4778e-01,  2.2095e+00,  1.0981e+00, -6.9826e-01,  1.9373e+00,
         7.1656e-01,  2.1135e+00, -8.7697e-01, -2.8182e-01,  3.8822e-01,
         4.6808e-01,  8.6699e-01, -1.5372e+00, -1.4107e-02, -3.2518e-01,
        -6.5052e-01, -9.9211e-01, -6.8172e-02,  6.4297e-01, -6.9022e-01,
        -2.3403e+00, -1.5715e+00, -1.1470e-02, -5.0536e-01, -1.6180e-01,
         7.4176e-01, -6.6837e-01,  6.8376e-01,  1.0455e+00, -1.4650e+00,
        -5.7787e-04,  5.9455e-01,  5.2933e-01,

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

The above example fails because determinant can only be found for matrices greater than `1D`.

The function `torch.det()` can be used for performing various matrix operations when we are working on different discrete mathematics problems.

---

## Conclusion

So this are the functions which were covered int his notebook.

- torch.randn()
- torch.sort()
- torch.pow()
- torch.round()
- torch.det()

And learnt about how to work with this functions with different set of parameters and came to a conclusion part of each function where it was explained about when to use which function. Also at last section of every functions an example portion was also covered where the exaplaination was given as when or in which scenario the above function breaks.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* Lecture 1 of [Deep Learning with PyTorch: Zero to GANs](https://jovian.ml/forum/t/lecture-1-pytorch-basics-linear-regression/1541)

In [ ]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [19]:
jovian.commit(message="Done with Assignment01")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "manishshah120/01-tensor-operations-be876" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/manishshah120/01-tensor-operations-be876


'https://jovian.ml/manishshah120/01-tensor-operations-be876'

                            **------The End-----**